# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2e3e636
_src_path: ./
accountname: quickplates
appname: react-example
description: React app example ⚛️
envprefix: REACT_EXAMPLE
imagename: apps/react-example
keyprefix: react-example
pages: app
pagesurl: https://quickplates.github.io/react-example
paths: false
port: 5173
registry: true
releases: true
reponame: react-example
repourl: https://github.com/quickplates/react-example
