---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 903735e
_src_path: ./
deploy: true
description: React project example ⚛️
envprefix: REACT_EXAMPLE
favicon: ⚛️
projectname: react-example
registry: true
username: quickplates
