---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4cb6d29
_src_path: ./
deploy: true
description: React project example ⚛️
envprefix: REACT_EXAMPLE
projectname: react-example
registry: true
releases: true
username: quickplates
